name: simple_shimmer
description: A simple widget with customizable shimmer-like fade animation between colors for skeleton screens
version: 0.1.0
repository: github.com/predatorx7/simple_shimmer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
